export const analyticsEvents = {
  coursesExploreClicked: "courses_explore_clicked",
  signInStarted: "sign_in_started",
  signUpStarted: "sign_up_started",
  courseContinueClicked: "course_continue_clicked",
  courseBookmarkClicked: "course_bookmark_clicked",
  courseModuleToggled: "course_module_toggled",
  courseLessonSelected: "course_lesson_selected",
  lessonViewed: "lesson_viewed",
  videoPlayed: "video_played",
  lessonTabChanged: "lesson_tab_changed",
  lessonResourceClicked: "lesson_resource_clicked",
  searchPerformed: "search_performed",
  catalogViewed: "catalog_viewed",
  courseViewed: "course_viewed",
  searchResultOpened: "search_result_opened",
  searchSortChanged: "search_sort_changed",
  videoProgress: "video_progress",
  lessonCompleted: "lesson_completed",
  lessonResumed: "lesson_resumed",
  lessonNavigated: "lesson_navigated",
  searchFailed: "search_failed",
} as const;
