import { PlayIcon } from "@sanity/icons";
import { defineArrayMember, defineField, defineType } from "sanity";

export const video = defineType({
  name: "video",
  title: "Video index",
  type: "document",
  icon: PlayIcon,
  readOnly: true,
  description:
    "Internal search data generated by the video ingestion pipeline.",
  fields: [
    defineField({
      name: "videoId",
      title: "Video ID",
      type: "string",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "url",
      title: "Video URL",
      type: "url",
      validation: (rule) => rule.required().uri({ scheme: ["https"] }),
    }),
    defineField({
      name: "provider",
      title: "Provider",
      type: "string",
      options: {
        list: ["youtube", "vimeo", "bunny"],
        layout: "radio",
      },
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "chapters",
      title: "Chapters",
      type: "array",
      of: [defineArrayMember({ type: "videoChapter" })],
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "chunks",
      title: "Transcript chunks",
      type: "array",
      of: [defineArrayMember({ type: "videoChunk" })],
      validation: (rule) => rule.required().min(1),
    }),
    defineField({
      name: "ingestedAt",
      title: "Ingested at",
      type: "datetime",
      validation: (rule) => rule.required(),
    }),
  ],
  preview: {
    select: { title: "videoId", chapters: "chapters", chunks: "chunks" },
    prepare({ title, chapters, chunks }) {
      return {
        title,
        subtitle: `${chapters?.length ?? 0} chapters / ${chunks?.length ?? 0} chunks`,
      };
    },
  },
});
